spring:
  application:
    name: mall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: 47.103.221.135:8848
    sentinel:
      transport:
        dashboard: localhost:8333
        port: 8719


  redis:
    host: 47.103.221.135
  task:
    execution:
      pool:
        core-size: 5
        max-size: 50
  session:
    store-type: redis

  rabbitmq:
    host: 47.103.221.135
    virtual-host: /
  thymeleaf:
    cache: false
#  task:
#    scheduling:
#      pool:
#        size: 5
server:
  port: 25000
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"



