spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.103.221.135:8848

  application:
    name: mall-search

  thymeleaf:
    cache: false
  session:
    store-type: redis

  redis:
    host: 47.103.221.135
    port: 6379
server:
  port: 12000