spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.103.221.135:8848
    alicloud:
      access-key: LTAI4G51DA6sWEJQ1LXWmrhL
      secret-key: IgAenHT03454WDc87JOa4RVLteZSYl
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: yimuziy-mall
server:
  port: 30000
